name: Deploy to AWS EC2
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14'

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            cd ~/ngjabach-blog
            git pull origin main

            # Backend
            cd backend
            echo "${{ secrets.BACKEND_ENV }}" > .env
            npm install
            /usr/bin/pm2 restart ngjabach-backend || /usr/bin/pm2 start npm --name "ngjabach-backend" -- start

            # Frontend
            cd ../frontend
            echo "${{ secrets.FRONTEND_ENV }}" > .env.local
            npm install
            npm run build
            /usr/bin/pm2 restart ngjabach-frontend || /usr/bin/pm2 start npm --name "ngjabach-frontend" -- start

            /usr/bin/pm2 save